# Generated by Django 5.1.2 on 2024-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('money_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('store', models.CharField(max_length=255)),
                ('gas_expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_of_day', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
