# Generated by Django 5.1.2 on 2024-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
