# Generated by Django 5.1.2 on 2024-11-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_trackingentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingentry',
            name='gas_expense',
        ),
    ]
